import { Resend } from "resend";

export const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendReportEmail({
  to,
  patientName,
  reportTitle,
  summary,
  attentionPoints,
  reportUrl,
}: {
  to: string;
  patientName: string;
  reportTitle: string;
  summary: string;
  attentionPoints: Array<{
    severity: string;
    title: string;
    description: string;
  }>;
  reportUrl: string;
}) {
  const attentionHtml = attentionPoints
    .map(
      (p) =>
        `<tr>
          <td style="padding:8px 12px;border-bottom:1px solid #E8DFD3;">
            <span style="display:inline-block;padding:2px 8px;border-radius:9999px;font-size:12px;font-weight:600;color:#fff;background:${
              p.severity === "high"
                ? "#C93B3B"
                : p.severity === "medium"
                ? "#D97757"
                : "#3A8F5C"
            };">${p.severity.toUpperCase()}</span>
          </td>
          <td style="padding:8px 12px;border-bottom:1px solid #E8DFD3;font-weight:600;color:#2D2016;">${p.title}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #E8DFD3;color:#6B5B4D;">${p.description}</td>
        </tr>`
    )
    .join("");

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#FAF7F2;font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:32px 24px;">
    <div style="text-align:center;margin-bottom:32px;">
      <h1 style="color:#D97757;font-size:24px;margin:0;">EmailP</h1>
      <p style="color:#9C8B7A;font-size:14px;margin:4px 0 0;">Laboratory Report</p>
    </div>

    <div style="background:#FFFFFF;border:1px solid #E8DFD3;border-radius:16px;padding:24px;margin-bottom:24px;">
      <h2 style="color:#2D2016;font-size:18px;margin:0 0 4px;">${reportTitle}</h2>
      <p style="color:#9C8B7A;font-size:14px;margin:0 0 16px;">Patient: ${patientName}</p>
      <hr style="border:none;border-top:1px solid #E8DFD3;margin:0 0 16px;">
      <h3 style="color:#6B5B4D;font-size:14px;font-weight:600;margin:0 0 8px;">Summary</h3>
      <p style="color:#2D2016;font-size:14px;line-height:1.6;margin:0;">${summary}</p>
    </div>

    ${
      attentionPoints.length > 0
        ? `<div style="background:#FFFFFF;border:1px solid #E8DFD3;border-radius:16px;padding:24px;margin-bottom:24px;">
        <h3 style="color:#6B5B4D;font-size:14px;font-weight:600;margin:0 0 12px;">Key Attention Points</h3>
        <table style="width:100%;border-collapse:collapse;">
          <thead>
            <tr style="text-align:left;">
              <th style="padding:8px 12px;border-bottom:2px solid #E8DFD3;color:#9C8B7A;font-size:12px;">Severity</th>
              <th style="padding:8px 12px;border-bottom:2px solid #E8DFD3;color:#9C8B7A;font-size:12px;">Issue</th>
              <th style="padding:8px 12px;border-bottom:2px solid #E8DFD3;color:#9C8B7A;font-size:12px;">Details</th>
            </tr>
          </thead>
          <tbody>${attentionHtml}</tbody>
        </table>
      </div>`
        : ""
    }

    <div style="text-align:center;margin-bottom:32px;">
      <a href="${reportUrl}" style="display:inline-block;padding:12px 32px;background:#D97757;color:#fff;font-weight:600;text-decoration:none;border-radius:12px;font-size:14px;">View Full Report</a>
    </div>

    <p style="text-align:center;color:#9C8B7A;font-size:12px;margin:0;">
      This email was generated by EmailP. Please do not reply to this email.
    </p>
  </div>
</body>
</html>`;

  const { data, error } = await resend.emails.send({
    from: process.env.RESEND_FROM_EMAIL || "EmailP <onboarding@resend.dev>",
    to,
    subject: `Lab Report: ${reportTitle}`,
    html,
  });

  if (error) throw new Error(error.message);
  return data;
}
