services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: emailp
      POSTGRES_PASSWORD: emailp
      POSTGRES_DB: emailp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
