import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { parseSearchParams, reportIdSchema } from "@/lib/validations";
import { format } from "date-fns";

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const parsed = parseSearchParams(req, reportIdSchema);
  if (!parsed.success) return parsed.response;
  const { id } = parsed.data;

  const report = await prisma.report.findUnique({
    where: { id, userId: session.user.id },
    include: {
      patient: true,
      bloodMetrics: { orderBy: { measuredAt: "asc" } },
      reportEmails: {
        include: { email: true },
        orderBy: { email: { date: "asc" } },
      },
    },
  });

  if (!report) {
    return NextResponse.json({ error: "Report not found" }, { status: 404 });
  }

  // Plain PDF: just merge all emails into one document
  if (report.reportType === "plain PDF") {
    const emails = report.reportEmails
      .map((re) => re.email)
      .filter((e) => e.body);

    const emailsHtml = emails
      .map(
        (e) => `
        <div style="margin-bottom:32px;padding-bottom:24px;border-bottom:1px solid #e5e5e5;">
          <div style="margin-bottom:12px;">
            <h3 style="font-size:16px;margin:0 0 4px;">${escapeHtml(e.subject || "(no subject)")}</h3>
            <div style="font-size:13px;color:#666;">
              ${e.from ? `<span>From: ${escapeHtml(e.from)}</span>` : ""}
              ${e.date ? `<span style="margin-left:12px;">${format(new Date(e.date), "MMMM d, yyyy 'at' h:mm a")}</span>` : ""}
            </div>
          </div>
          <div style="font-size:14px;color:#333;white-space:pre-wrap;line-height:1.7;">${escapeHtml(e.body!)}</div>
        </div>`
      )
      .join("");

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(report.title)}</title>
  <style>
    @media print {
      body { margin: 0; }
      @page { margin: 1.5cm; }
    }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #1a1a1a; max-width: 800px; margin: 0 auto; padding: 40px 24px; line-height: 1.6; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .meta { color: #666; font-size: 14px; margin-bottom: 32px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(report.title)}</h1>
  <div class="meta">
    <strong>Patient:</strong> ${escapeHtml(report.patient.name)}
    ${report.patient.governmentId ? ` &nbsp;|&nbsp; <strong>ID:</strong> ${escapeHtml(report.patient.governmentId)}` : ""}
    &nbsp;|&nbsp; <strong>Date:</strong> ${format(new Date(report.createdAt), "MMMM d, yyyy")}
    &nbsp;|&nbsp; <strong>Emails:</strong> ${emails.length}
  </div>

  ${emailsHtml}

  <div style="margin-top:48px;padding-top:16px;border-top:1px solid #e5e5e5;font-size:12px;color:#999;">
    Generated by EmailP &mdash; ${format(new Date(), "MMMM d, yyyy 'at' h:mm a")}
  </div>

  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

    return new NextResponse(html, {
      headers: { "Content-Type": "text/html; charset=utf-8" },
    });
  }

  // Standard AI report PDF
  const attentionPoints: Array<{
    severity: string;
    title: string;
    description: string;
    relatedMetrics: string[];
    recommendations: string[];
  }> = report.attentionPoints ? JSON.parse(report.attentionPoints) : [];

  const severityColor = (s: string) =>
    s === "high" ? "#DC2626" : s === "medium" ? "#F59E0B" : "#22C55E";

  const metricsRows = report.bloodMetrics
    .map(
      (m) => `<tr>
        <td>${m.metricName}</td>
        <td style="text-align:right;font-weight:600;${m.isAbnormal ? "color:#DC2626;" : ""}">${m.value}</td>
        <td>${m.unit}</td>
        <td>${m.referenceMin != null && m.referenceMax != null ? `${m.referenceMin} - ${m.referenceMax}` : "-"}</td>
        <td>${format(new Date(m.measuredAt), "MMM d, yyyy")}</td>
      </tr>`
    )
    .join("");

  const attentionHtml = attentionPoints
    .map(
      (ap) => `
      <div style="margin-bottom:16px;padding:12px 16px;border-left:4px solid ${severityColor(ap.severity)};background:#fafafa;border-radius:0 8px 8px 0;">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:4px;">
          <span style="display:inline-block;padding:2px 8px;border-radius:9999px;font-size:11px;font-weight:600;color:white;background:${severityColor(ap.severity)};text-transform:uppercase;">${ap.severity}</span>
          <strong>${ap.title}</strong>
        </div>
        <p style="margin:4px 0;font-size:14px;color:#444;">${ap.description}</p>
        ${ap.recommendations.length ? `<ul style="margin:6px 0 0;padding-left:20px;font-size:13px;color:#555;">${ap.recommendations.map((r) => `<li>${r}</li>`).join("")}</ul>` : ""}
      </div>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Report - ${report.patient.name}</title>
  <style>
    @media print {
      body { margin: 0; }
      .no-print { display: none !important; }
      @page { margin: 1.5cm; }
    }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #1a1a1a; max-width: 800px; margin: 0 auto; padding: 40px 24px; line-height: 1.6; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    h2 { font-size: 18px; margin-top: 32px; margin-bottom: 12px; border-bottom: 2px solid #e5e5e5; padding-bottom: 6px; }
    .meta { color: #666; font-size: 14px; margin-bottom: 32px; }
    .summary { font-size: 15px; color: #333; white-space: pre-wrap; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e5e5e5; }
    th { font-weight: 600; background: #f9f9f9; }
  </style>
</head>
<body>
  <h1>${report.title}</h1>
  <div class="meta">
    <strong>Patient:</strong> ${report.patient.name}
    ${report.patient.governmentId ? ` &nbsp;|&nbsp; <strong>ID:</strong> ${report.patient.governmentId}` : ""}
    &nbsp;|&nbsp; <strong>Date:</strong> ${format(new Date(report.createdAt), "MMMM d, yyyy")}
  </div>

  ${report.summary ? `<h2>Summary</h2><div class="summary">${report.summary}</div>` : ""}

  ${
    report.bloodMetrics.length > 0
      ? `<h2>Blood Metrics</h2>
    <table>
      <thead><tr><th>Metric</th><th style="text-align:right">Value</th><th>Unit</th><th>Reference</th><th>Date</th></tr></thead>
      <tbody>${metricsRows}</tbody>
    </table>`
      : ""
  }

  ${attentionPoints.length > 0 ? `<h2>Attention Points</h2>${attentionHtml}` : ""}

  <div style="margin-top:48px;padding-top:16px;border-top:1px solid #e5e5e5;font-size:12px;color:#999;">
    Generated by EmailP &mdash; ${format(new Date(), "MMMM d, yyyy 'at' h:mm a")}
  </div>

  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

  return new NextResponse(html, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}
